In [1]:
# !pip install opencv-python

In [2]:
# !pip install tensorflow

In [3]:
# !pip install keras

In [4]:
# !pip install Pillow

In [5]:
import cv2
import tensorflow
import keras
from PIL import Image
import numpy as np
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

In [6]:
webcam = cv2.VideoCapture(1)
webcam

<VideoCapture 000001E62C636090>

In [7]:
face_cascade = "haarcascade_frontalface_default.xml"
success, image_bgr = webcam.read()
image_rgb = cv2.cvtColor(image_bgr,cv2.COLOR_BGR2RGB)
face_classifier = cv2.CascadeClassifier(face_cascade)

# Face Detection

In [ ]:
np.set_printoptions(suppress=True)
model = load_model('face_mask_s224.h5')
size = (224, 224)
    
while True:
    success, image_bgr = webcam.read()
    image_org = image_bgr.copy()
    image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
    image_rgb = cv2.cvtColor(image_bgr,cv2.COLOR_BGR2RGB)
    faces = face_classifier.detectMultiScale(image_bw)
    
    for face in faces:
        x, y, w, h = face
        cface_rgb = Image.fromarray(image_rgb[y:y+h,x:x+w])
        data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
        image = cface_rgb
        image = ImageOps.fit(image, size, Image.ANTIALIAS)
        image_array = np.asarray(image)
        normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
        data[0] = normalized_image_array
        prediction = model.predict(data)
        print(prediction)
        
        if ((prediction[0][0] > prediction[0][1]) & (prediction[0][0] > 0.97)):
                cv2.putText(image_bgr,'Masked',(x,y-7),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,255,0),2)
                cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0, 255, 0), 2)
        elif prediction[0][1] > 0.97:
                cv2.putText(image_bgr,'Non-Masked',(x,y-7),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),2)
                cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0,0,255), 2)
            
    cv2.imshow("Mask Detection", image_bgr)
    cv2.waitKey(1) 

[[0.00000386 0.9999962 ]]
[[0.00182712 0.9981729 ]]
[[0.00006291 0.99993706]]
[[0.00001305 0.9999869 ]]
[[0.0000167 0.9999833]]
[[0.0000167 0.9999833]]
[[0.00020291 0.99979717]]
[[0.00002753 0.99997246]]
[[0.00021181 0.9997882 ]]
[[0.00000641 0.99999356]]
[[0.00015291 0.99984705]]
[[0.00022959 0.99977046]]
[[0.00131111 0.9986889 ]]
[[0.00007471 0.99992526]]
[[0.00007471 0.99992526]]
[[0.00000273 0.99999726]]
[[0.00001034 0.9999896 ]]
[[0.00002709 0.99997294]]
[[0.0000399  0.99996006]]
[[0.0000399  0.99996006]]
[[0.000012   0.99998796]]
[[0.0000066  0.99999344]]
[[0.00000096 0.99999905]]
[[0.0000011 0.9999989]]
[[0.00000006 1.        ]]
[[0.00013813 0.99986184]]
[[0.00000036 0.99999964]]
[[0.00000509 0.9999949 ]]
[[0.00000006 0.9999999 ]]
[[0.00000292 0.999997  ]]
[[0.00020868 0.9997913 ]]
[[0.00000161 0.99999833]]
[[0.00000002 1.        ]]
[[0.00000002 1.        ]]
[[0.0000008  0.99999917]]
[[0.00000021 0.99999976]]
[[0.00000028 0.99999976]]
[[0.00061744 0.9993825 ]]
[[0.00007768 0.999

[[0.00005554 0.99994445]]
[[0.00000149 0.99999845]]
[[0.0141431 0.9858569]]
[[0.00012357 0.9998764 ]]
[[0.00012357 0.9998764 ]]
[[0.00058264 0.9994174 ]]
[[0.00058264 0.9994174 ]]
[[0.00021963 0.99978036]]
[[0.00021963 0.99978036]]
[[0.00270639 0.99729365]]
[[0.00329132 0.99670863]]
[[0.02332041 0.97667956]]
[[0.00001508 0.99998486]]
[[0.00016459 0.9998354 ]]
[[0.00011179 0.9998882 ]]
[[0.00166698 0.99833304]]
[[0.01219619 0.9878038 ]]
[[0.00891036 0.9910896 ]]
[[0.00503768 0.99496233]]
[[0.01059475 0.9894052 ]]
[[0.3547517  0.64524823]]
[[0.04466347 0.9553366 ]]
[[0.63666916 0.36333078]]
[[0.3453736 0.6546264]]
[[0.14892112 0.85107887]]
[[0.36227322 0.6377268 ]]
[[0.08290303 0.917097  ]]
[[0.01776603 0.98223394]]
[[0.0000328 0.9999672]]
[[0.00016059 0.9998394 ]]
[[0.00012643 0.9998735 ]]
[[0.00159916 0.99840087]]
[[0.1993607  0.80063933]]
[[0.0001739  0.99982613]]
[[0.00076916 0.99923086]]
[[0.00601351 0.9939865 ]]
[[0.00023272 0.99976724]]
[[0.0019501  0.99804986]]
[[0.00042048 0.999

[[0.00013731 0.9998627 ]]
[[0.00013731 0.9998627 ]]
[[0.00008086 0.9999192 ]]
[[0.02017631 0.9798237 ]]
[[0.00114048 0.9988595 ]]
[[0.00262746 0.9973725 ]]
[[0.00262746 0.9973725 ]]
[[0.01018758 0.98981243]]
[[0.00008624 0.9999138 ]]
[[0.00046255 0.99953747]]
[[0.0001052  0.99989474]]
[[0.0001052  0.99989474]]
[[0.00006536 0.9999347 ]]
[[0.0001654  0.99983454]]
[[0.00022273 0.99977726]]
[[0.00847505 0.9915249 ]]
[[0.01357651 0.98642343]]
[[0.00428278 0.9957172 ]]
[[0.0008129  0.99918705]]
[[0.0008129  0.99918705]]
[[0.00465861 0.9953414 ]]
[[0.00098795 0.999012  ]]
[[0.00098795 0.999012  ]]
[[0.00265064 0.9973494 ]]
[[0.00000168 0.99999833]]
[[0.00020142 0.9997986 ]]
[[0.01816688 0.9818331 ]]
[[0.00018683 0.99981314]]
[[0.00018683 0.99981314]]
[[0.01775366 0.9822464 ]]
[[0.00001539 0.9999846 ]]
[[0.0000554  0.99994457]]
[[0.0000554  0.99994457]]
[[0.00000894 0.99999106]]
[[0.00000894 0.99999106]]
[[0.00000004 1.        ]]
[[0.00000629 0.9999937 ]]
[[0. 1.]]
[[0. 1.]]
[[0.00000007 0.999

[[0.00001575 0.99998426]]
[[0.00001781 0.99998224]]
[[0.00000371 0.9999963 ]]
[[0.00000064 0.9999994 ]]
[[0.0000023  0.99999774]]
[[0.00017298 0.9998271 ]]
[[0.0000004  0.99999964]]
[[0.0000011 0.9999989]]
[[0.00000441 0.9999956 ]]
[[0.00000086 0.99999917]]
[[0.00000086 0.99999917]]
[[0.0000003  0.99999964]]
[[0.00000032 0.99999964]]
[[0.00000052 0.9999995 ]]
[[0.01309541 0.98690456]]
[[0.01309541 0.98690456]]
[[0.00022921 0.9997708 ]]
[[0.00000295 0.999997  ]]
[[0.00000072 0.9999993 ]]
[[0.00000072 0.9999993 ]]
[[0.00000014 0.9999999 ]]
[[0.0000064  0.99999356]]
[[0.00000026 0.99999976]]
[[0.00000026 0.99999976]]
[[0.00000059 0.9999994 ]]
[[0.00000003 1.        ]]
[[0.00000004 1.        ]]
[[0.00000033 0.99999964]]
[[0.00000033 0.99999964]]
[[0.00000022 0.99999976]]
[[0.00000008 0.9999999 ]]
[[0.00000065 0.9999994 ]]
[[0.00000065 0.9999994 ]]
[[0.00005404 0.999946  ]]
[[0.00000116 0.9999988 ]]
[[0.972024   0.02797601]]
[[0.00000815 0.9999919 ]]
[[0.8683325  0.13166744]]
[[0.00000804 0

[[0.8619973  0.13800272]]
[[0.9969894  0.00301057]]
[[0.9999752  0.00002483]]
[[0.9999187  0.00008127]]
[[0.9999187  0.00008127]]
[[0.9999217  0.00007836]]
[[0.999877   0.00012303]]
[[0.99993694 0.000063  ]]
[[0.99993694 0.000063  ]]
[[0.00065446 0.9993455 ]]
[[0.9998592  0.00014081]]
[[0.99998605 0.00001398]]
[[0.9463158  0.05368422]]
[[0.9463158  0.05368422]]
[[0.9999229  0.00007708]]
[[0.9989893  0.00101071]]
[[0.998638   0.00136202]]
[[0.99990225 0.00009776]]
[[0.99987996 0.00012002]]
[[0.999874   0.00012599]]
[[0.99968195 0.00031812]]
[[0.9998913  0.00010875]]
[[0.999403   0.00059696]]
[[0.9999516  0.00004842]]
[[0.9999833 0.0000167]]
[[0.9917672  0.00823278]]
[[0.99614894 0.00385104]]
[[0.00029843 0.99970156]]
[[0.9977277 0.0022723]]
[[0.9999049  0.00009513]]
[[0.9999049  0.00009513]]
[[0.00458245 0.9954176 ]]
[[0.05496049 0.9450395 ]]
[[0.9996426  0.00035739]]
[[0.00315931 0.9968407 ]]
[[0.7956297  0.20437032]]
[[0.01854766 0.9814524 ]]
[[0.00084035 0.9991597 ]]
[[0.00000291 0.9

[[0.00150661 0.99849343]]
[[0.00002794 0.9999721 ]]
[[0.00014112 0.99985886]]
[[0.0000102  0.99998975]]
[[0.0000382  0.99996185]]
[[0.00128395 0.9987161 ]]
[[0.00107705 0.9989229 ]]
[[0.01082417 0.98917586]]
[[0.00019313 0.99980694]]
[[0.00019313 0.99980694]]
[[0.00076165 0.9992384 ]]
[[0.00019761 0.9998024 ]]
[[0.00013529 0.9998647 ]]
[[0.00005647 0.9999435 ]]
[[0.00005647 0.9999435 ]]
[[0.00014848 0.99985147]]
[[0.00532467 0.9946753 ]]
[[0.00009214 0.99990785]]
[[0.0005036  0.99949634]]
[[0.0005036  0.99949634]]
[[0.00010478 0.9998952 ]]
[[0.00025523 0.9997447 ]]
[[0.00027653 0.9997235 ]]
[[0.00004826 0.9999517 ]]
[[0.00010699 0.99989295]]
[[0.00057216 0.99942786]]
[[0.00003594 0.999964  ]]
[[0.00003594 0.999964  ]]
[[0.00296143 0.9970386 ]]
[[0.00004636 0.9999536 ]]
[[0.00009768 0.99990237]]
[[0.0000032 0.9999968]]
[[0.00247681 0.9975231 ]]
[[0.00001307 0.9999869 ]]
[[0.00038662 0.99961346]]
[[0.00008125 0.9999187 ]]
[[0.00000715 0.99999285]]
[[0.00013376 0.99986625]]
[[0.00003902 0

[[0.00036425 0.9996357 ]]
[[0.00019554 0.99980444]]
[[0.00013325 0.9998667 ]]
[[0.00002415 0.9999758 ]]
[[0.00000517 0.9999949 ]]
[[0.00000517 0.9999949 ]]
[[0.00003269 0.99996734]]
[[0.00105355 0.9989465 ]]
[[0.00002278 0.99997723]]
[[0.00002278 0.99997723]]
[[0.00000127 0.9999987 ]]
[[0.00000864 0.9999914 ]]
[[0.00000864 0.9999914 ]]
[[0.0000003  0.99999976]]
[[0.00000017 0.9999999 ]]
[[0.00007353 0.99992645]]
[[0.00000811 0.9999919 ]]
[[0.00280509 0.9971949 ]]
[[0.00002459 0.99997544]]
[[0.00000384 0.9999962 ]]
[[0.00002872 0.9999713 ]]
[[0.00018584 0.9998142 ]]
[[0.00018584 0.9998142 ]]
[[0.00000116 0.9999988 ]]
[[0.00000059 0.9999994 ]]
[[0.00000059 0.9999994 ]]
[[0.00004838 0.9999516 ]]
[[0.00000016 0.9999999 ]]
[[0.00065856 0.9993414 ]]
[[0.00065856 0.9993414 ]]
[[0.00000158 0.99999845]]
[[0.00000327 0.9999968 ]]
[[0.00010546 0.9998945 ]]
[[0.00010546 0.9998945 ]]
[[0.00000007 0.9999999 ]]
[[0.00000007 0.9999999 ]]
[[0.00000037 0.99999964]]
[[0.00006329 0.9999367 ]]
[[0.00006329

[[0.00000581 0.99999416]]
[[0.00000004 1.        ]]
[[0.00000004 1.        ]]
[[0.00620847 0.9937915 ]]
[[0.00000012 0.9999999 ]]
[[0.00345194 0.9965481 ]]
[[0. 1.]]
[[0.00000388 0.99999607]]
[[0.00000012 0.9999999 ]]
[[0.00000012 0.9999999 ]]
[[0. 1.]]
[[0.00000521 0.99999475]]
[[0.00013439 0.99986553]]
[[0.00013439 0.99986553]]
[[0.00006002 0.9999399 ]]
[[0.00000003 1.        ]]
[[0.00000003 1.        ]]
[[0.00000017 0.9999999 ]]
[[0.00009424 0.9999057 ]]
[[0.00005693 0.999943  ]]
[[0.00005693 0.999943  ]]
[[0.00000004 1.        ]]
[[0.00000001 1.        ]]
[[0.00063581 0.9993642 ]]
[[0.00000095 0.99999905]]
[[0.00063581 0.9993642 ]]
[[0.00000095 0.99999905]]
[[0.00000309 0.9999969 ]]
[[0.0000007 0.9999993]]
[[0.00004591 0.9999541 ]]
[[0.00000005 1.        ]]
[[0.00000005 1.        ]]
[[0.00000002 1.        ]]
[[0.00000108 0.9999989 ]]
[[0.00000108 0.9999989 ]]
[[0.00000009 0.9999999 ]]
[[0.00000034 0.99999964]]
[[0.00000094 0.99999905]]
[[0.00000094 0.99999905]]
[[0.00000002 1.     

[[0.01850318 0.9814968 ]]
[[0.99986255 0.00013744]]
[[0.9997856  0.00021441]]
[[0.00014655 0.9998534 ]]
[[0.99996185 0.00003819]]
[[0.9999875  0.00001253]]
[[0.99999917 0.00000081]]
[[0.9988135  0.00118653]]
[[0.9988135  0.00118653]]
[[0.9998198  0.00018025]]
[[0.9994634  0.00053659]]
[[0.9999713  0.00002877]]
[[0.9999713  0.00002877]]
[[0.9999994  0.00000063]]
[[0.9999994  0.00000063]]
[[0.9999833  0.00001675]]
[[0.99999535 0.00000463]]
[[0.99999535 0.00000463]]
[[0.00000384 0.9999962 ]]
[[0.99997854 0.0000214 ]]
[[0.0407128 0.9592872]]
[[0.01365917 0.9863409 ]]
[[0.99998295 0.00001704]]
[[0.99988556 0.00011448]]
[[0.9999944  0.00000558]]
[[0.9999944  0.00000558]]
[[0.99322414 0.00677585]]
[[0.9997695  0.00023052]]
[[0.9997695  0.00023052]]
[[0.9907103  0.00928967]]
[[0.9999993  0.00000072]]
[[0.9999989  0.00000107]]
[[0.9999989  0.00000107]]
[[0.9999963  0.00000367]]
[[0.00065142 0.9993486 ]]
[[0.0008033 0.9991967]]
[[0.0008033 0.9991967]]
[[0.03677572 0.96322435]]
[[0.00270781 0.997

[[0.02214545 0.9778545 ]]
[[0.00006237 0.99993765]]
[[0.00000286 0.99999714]]
[[0.000315   0.99968505]]
[[0.01291615 0.9870839 ]]
[[0.00000348 0.99999654]]
[[0.0074189 0.9925811]]
[[0.00000006 0.9999999 ]]
[[0.00007941 0.9999206 ]]
[[0.00002981 0.9999702 ]]
[[0.00004693 0.99995303]]
[[0.00002981 0.9999702 ]]
[[0.00004693 0.99995303]]
[[0.00001074 0.9999893 ]]
[[0.00203731 0.9979627 ]]
[[0.00000619 0.9999938 ]]
[[0.00064031 0.99935967]]
[[0.00081909 0.99918085]]
[[0.00000035 0.99999964]]
[[0.00067952 0.9993205 ]]
[[0.00000076 0.9999993 ]]
[[0.00000226 0.99999774]]
[[0.00002248 0.99997747]]
[[0.03154222 0.96845776]]
[[0.02678564 0.9732144 ]]
[[0.0000353 0.9999647]]
[[0.00000116 0.9999988 ]]
[[0.01426754 0.9857325 ]]
[[0.00000036 0.99999964]]
[[0.00000867 0.9999913 ]]
[[0.0000094 0.9999906]]
[[0.00025132 0.99974865]]
[[0.00004658 0.9999534 ]]
[[0.00001724 0.9999827 ]]
[[0.001301   0.99869895]]
[[0.00000095 0.99999905]]
[[0.00126516 0.9987349 ]]
[[0.00000152 0.99999845]]
[[0.00106451 0.998

[[0.999134   0.00086604]]
[[0.999134   0.00086604]]
[[0.13268147 0.8673186 ]]
[[0.00064414 0.99935585]]
[[0.00007121 0.99992883]]
[[0.00007121 0.99992883]]
[[0.00018647 0.9998136 ]]
[[0.00001079 0.99998915]]
[[0.00000606 0.9999939 ]]
[[0.00000427 0.9999957 ]]
[[0.00000029 0.99999976]]
[[0.99150324 0.00849676]]
[[0.00029195 0.999708  ]]
[[0.00029195 0.999708  ]]
[[0.00046153 0.99953854]]
[[0.06741901 0.932581  ]]
[[0.02041384 0.9795862 ]]
[[0.02322793 0.976772  ]]
[[0.02322793 0.976772  ]]
[[0.00024024 0.99975973]]
[[0.00024024 0.99975973]]
[[0.00032018 0.9996798 ]]
[[0.00005197 0.999948  ]]
[[0.00016707 0.99983287]]
[[0.00016707 0.99983287]]
[[0.00611307 0.9938869 ]]
[[0.00072324 0.9992768 ]]
[[0.00072324 0.9992768 ]]
[[0.00268463 0.99731535]]
[[0.00047656 0.9995234 ]]
[[0.0000068 0.9999932]]
[[0.99998367 0.00001636]]
[[0.99998367 0.00001636]]
[[0.00002962 0.99997044]]
[[0.9994388  0.00056121]]
[[0.00000415 0.9999958 ]]
[[0.9998254 0.0001746]]
[[0.9991899  0.00081012]]
[[0.9990677  0.0

[[0.0000058  0.99999416]]
[[0.00000001 1.        ]]
[[0.00000381 0.9999962 ]]
[[0.00002631 0.99997365]]
[[0.00000131 0.9999987 ]]
[[0.00000131 0.9999987 ]]
[[0.00000326 0.9999968 ]]
[[0.00000326 0.9999968 ]]
[[0.00000215 0.99999785]]
[[0.0000002  0.99999976]]
[[0.00000041 0.99999964]]
[[0.00000165 0.99999833]]
[[0.00000165 0.99999833]]
[[0.0001267 0.9998733]]
[[0.0000008  0.99999917]]
[[0.000003 0.999997]]
[[0.0000053  0.99999475]]
[[0.00001882 0.99998116]]
[[0.00013393 0.999866  ]]
[[0.00001093 0.99998903]]
[[0.00000096 0.99999905]]
[[0.00000431 0.9999957 ]]
[[0.00000335 0.99999666]]
[[0.00014232 0.99985766]]
[[0.00014232 0.99985766]]
[[0.00103237 0.99896765]]
[[0.00026147 0.9997385 ]]
[[0.00024893 0.99975103]]
[[0.00000587 0.99999416]]
[[0.00004588 0.9999541 ]]
[[0.00000042 0.9999995 ]]
[[0.00000051 0.9999995 ]]
[[0.00000051 0.9999995 ]]
[[0.00002421 0.9999758 ]]
[[0.00003826 0.99996173]]
[[0.0000046  0.99999535]]
[[0.0000046  0.99999535]]
[[0.00003088 0.9999691 ]]
[[0.00001517 0.999

[[0.00000068 0.9999993 ]]
[[0.00000004 1.        ]]
[[0.00000034 0.99999964]]
[[0.00000034 0.99999964]]
[[0.00000009 0.9999999 ]]
[[0.00000627 0.9999937 ]]
[[0.00000627 0.9999937 ]]
[[0.00000045 0.9999995 ]]
[[0.00000557 0.9999944 ]]
[[0.00000196 0.9999981 ]]
[[0.00000196 0.9999981 ]]
[[0.00000192 0.9999981 ]]
[[0.00000115 0.9999988 ]]
[[0.00000511 0.9999949 ]]
[[0.00000511 0.9999949 ]]
[[0.00000027 0.99999976]]
[[0.00000027 0.99999976]]
[[0.00000006 1.        ]]
[[0.00000012 0.9999999 ]]
[[0.00000175 0.9999982 ]]
[[0.00000045 0.9999995 ]]
[[0.00000057 0.9999994 ]]
[[0.00000018 0.9999999 ]]
[[0.00000018 0.9999999 ]]
[[0.00000036 0.99999964]]
[[0.00000014 0.9999999 ]]
[[0.00000014 0.9999999 ]]
[[0.00000002 1.        ]]
[[0.00000027 0.99999976]]
[[0.00000227 0.99999774]]
[[0.00000227 0.99999774]]
[[0.00002426 0.9999757 ]]
[[0.00001252 0.9999875 ]]
[[0.00001568 0.99998426]]
[[0.00001568 0.99998426]]
[[0.00000019 0.99999976]]
[[0.00000007 0.9999999 ]]
[[0.00000072 0.9999993 ]]
[[0.00000072

[[0.9999387 0.0000613]]
[[0.9999387 0.0000613]]
[[0.9999882  0.00001179]]
[[0.99998915 0.00001079]]
[[0.9999101  0.00008982]]
[[0.9999101  0.00008982]]
[[0.9999759  0.00002403]]
[[0.99997294 0.00002702]]
[[0.9997131  0.00028683]]
[[0.9997131  0.00028683]]
[[0.9999796  0.00002039]]
[[0.9999653  0.00003471]]
[[0.9999653  0.00003471]]
[[0.9999243  0.00007564]]
[[0.99956113 0.0004389 ]]
[[0.99966323 0.00033676]]
[[0.99966323 0.00033676]]
[[0.99627006 0.0037299 ]]
[[0.99627006 0.0037299 ]]
[[0.00015924 0.99984074]]
[[0.00015924 0.99984074]]
[[0.99986815 0.0001318 ]]
[[0.0000078  0.99999225]]
[[0.99932206 0.00067797]]
[[0.9983929  0.00160706]]
[[0.9983929  0.00160706]]
[[0.9801875  0.01981253]]
[[0.00225587 0.9977442 ]]
[[0.9980572 0.0019428]]
[[0.9999355  0.00006452]]
[[0.99985695 0.00014303]]
[[0.99985695 0.00014303]]
[[0.00009361 0.9999064 ]]
[[0.00009361 0.9999064 ]]
[[0.0000637  0.99993634]]
[[0.0000637  0.99993634]]
[[0.00004748 0.99995255]]
[[0.01386236 0.98613757]]
[[0.0003726  0.999

[[0.00020344 0.99979657]]
[[0.99941254 0.00058747]]
[[0.00020344 0.99979657]]
[[0.99941254 0.00058747]]
[[0.01876735 0.98123264]]
[[0.01876735 0.98123264]]
[[0.15163986 0.8483601 ]]
[[0.00014349 0.9998565 ]]
[[0.00014349 0.9998565 ]]
[[0.00271921 0.9972807 ]]
[[0.00001886 0.99998116]]
[[0.00001886 0.99998116]]
[[0.00003198 0.99996805]]
[[0.00015982 0.99984014]]
[[0.00015982 0.99984014]]
[[0.00004764 0.9999523 ]]
[[0.0001673  0.99983263]]
[[0.0001673  0.99983263]]
[[0.00105918 0.9989409 ]]
[[0.00105918 0.9989409 ]]
[[0.00028517 0.9997148 ]]
[[0.0002732  0.99972683]]
[[0.00001042 0.9999896 ]]
[[0.00001042 0.9999896 ]]
[[0.73216426 0.2678358 ]]
[[0.73216426 0.2678358 ]]
[[0.91270125 0.08729874]]
[[0.91270125 0.08729874]]
[[0.9956306  0.00436941]]
[[0.9999616  0.00003836]]
[[0.9999616  0.00003836]]
[[0.9971661  0.00283387]]
[[0.9994822  0.00051786]]
[[0.99803156 0.00196839]]
[[0.99803156 0.00196839]]
[[0.00012971 0.9998703 ]]
[[0.9989536  0.00104639]]
[[0.00023045 0.9997695 ]]
[[0.00023045

[[0.00051674 0.9994832 ]]
[[0.00036911 0.9996309 ]]
[[0.00001193 0.9999881 ]]
[[0.00002427 0.9999757 ]]
[[0.00011885 0.99988115]]
[[0.00036736 0.9996326 ]]
[[0.00018895 0.9998111 ]]
[[0.00000145 0.99999857]]
[[0.00000588 0.99999416]]
[[0.00000588 0.99999416]]
[[0.00000401 0.99999595]]
[[0.00002084 0.99997914]]
[[0.00013261 0.9998673 ]]
[[0.00000232 0.99999774]]
[[0.00000361 0.9999964 ]]
[[0.00000107 0.9999989 ]]
[[0.00000535 0.99999464]]
[[0.0000044 0.9999956]]
[[0.00000005 1.        ]]
[[0.00000005 1.        ]]
[[0.00000002 1.        ]]
[[0.00000015 0.9999999 ]]
[[0.00000007 0.9999999 ]]
[[0.00000841 0.99999154]]
[[0.00000804 0.999992  ]]
[[0.00000533 0.99999464]]
[[0.00004861 0.99995136]]
[[0.00001793 0.9999821 ]]
[[0.00001252 0.9999875 ]]
[[0.00001252 0.9999875 ]]
[[0.0000008  0.99999917]]
[[0.00000218 0.99999785]]
[[0.00000395 0.99999607]]
[[0.00035843 0.99964154]]
[[0.00009711 0.99990284]]
[[0.00001127 0.9999887 ]]
[[0.00008458 0.99991536]]
[[0.0000414  0.99995863]]
[[0.0000414  0

[[0.00022586 0.99977416]]
[[0.00000864 0.9999914 ]]
[[0.00002578 0.99997425]]
[[0.00012394 0.999876  ]]
[[0.00008501 0.999915  ]]
[[0.00000773 0.99999225]]
[[0.00000318 0.9999968 ]]
[[0.00047808 0.999522  ]]
[[0.00000273 0.99999726]]
[[0.00042391 0.99957603]]
[[0.00005663 0.9999434 ]]
[[0.00000199 0.999998  ]]
[[0.00001103 0.9999889 ]]
[[0.00002622 0.9999738 ]]
[[0.00005123 0.99994874]]
[[0.00005123 0.99994874]]
[[0.0001178 0.9998822]]
[[0.0000028  0.99999714]]
[[0.00036926 0.9996307 ]]
[[0.00003082 0.9999691 ]]
[[0.000008 0.999992]]
[[0.0000209  0.99997914]]
[[0.00000473 0.99999523]]
[[0.00000001 1.        ]]
[[0.00001277 0.99998724]]
[[0.00000197 0.9999981 ]]
[[0.00000089 0.99999917]]
[[0.00000616 0.9999938 ]]
[[0.00000044 0.9999995 ]]
[[0.00000081 0.99999917]]
[[0.00261241 0.9973876 ]]
[[0.00007622 0.9999238 ]]
[[0.00000309 0.9999969 ]]
[[0.00004803 0.99995196]]
[[0.0000051 0.9999949]]
[[0.00000072 0.9999993 ]]
[[0.00000061 0.9999994 ]]
[[0.0001371 0.9998629]]
[[0.00001133 0.9999887

[[0.03468721 0.96531284]]
[[0.00040369 0.9995963 ]]
[[0.00000034 0.99999964]]
[[0.00013606 0.99986386]]
[[0.00013606 0.99986386]]
[[0.00000084 0.99999917]]
[[0.00001523 0.99998474]]
[[0.00000183 0.9999982 ]]
[[0.00000183 0.9999982 ]]
[[0.00107463 0.9989254 ]]
[[0.23252515 0.7674749 ]]
[[0.00013217 0.9998678 ]]
[[0.00018017 0.9998198 ]]
[[0.0000004  0.99999964]]
[[0.00000075 0.9999993 ]]
[[0.00000014 0.9999999 ]]
[[0.00000023 0.99999976]]
[[0.0000001 0.9999999]]
[[0.00002617 0.9999738 ]]
[[0.00000209 0.99999785]]
[[0.00000141 0.99999857]]
[[0.00000141 0.99999857]]
[[0.00000495 0.999995  ]]
[[0.00000725 0.9999927 ]]
[[0.00000014 0.9999999 ]]
[[0.00008539 0.99991465]]
[[0.00002855 0.9999715 ]]
[[0.00001336 0.99998665]]
[[0.00000042 0.9999995 ]]
[[0.00000012 0.9999999 ]]
[[0.00000012 0.9999999 ]]
[[0.00001648 0.99998355]]
[[0.00000589 0.99999416]]
[[0.00000015 0.9999999 ]]
[[0.00006169 0.99993837]]
[[0.00005152 0.9999485 ]]
[[0.00018658 0.9998135 ]]
[[0.00000207 0.999998  ]]
[[0.0014016 0.

[[0.00036096 0.99963903]]
[[0.00005318 0.99994683]]
[[0.0000082 0.9999918]]
[[0.00000058 0.9999994 ]]
[[0.00003128 0.99996877]]
[[0.00000865 0.9999913 ]]
[[0.00000865 0.9999913 ]]
[[0.00003701 0.9999629 ]]
[[0.00000026 0.99999976]]
[[0.00092232 0.9990777 ]]
[[0.01907274 0.9809272 ]]
[[0.00002319 0.99997675]]
[[0.00054511 0.9994549 ]]
[[0.00000698 0.99999297]]
[[0.00160529 0.99839467]]
[[0.00000014 0.9999999 ]]
[[0.00000014 0.9999999 ]]
[[0.00000212 0.99999785]]
[[0.00000556 0.9999944 ]]
[[0.00013321 0.9998667 ]]
[[0.00000198 0.999998  ]]
[[0.00005832 0.9999417 ]]
[[0.00000004 1.        ]]
[[0.00016053 0.9998394 ]]
[[0.00000206 0.999998  ]]
[[0.00000206 0.999998  ]]
[[0.00000467 0.99999535]]
[[0.000006   0.99999404]]
[[0.00000203 0.999998  ]]
[[0.00000099 0.99999905]]
[[0.00001787 0.9999821 ]]
[[0.00002857 0.9999714 ]]
[[0.00000226 0.99999774]]
[[0.00000056 0.9999994 ]]
[[0.00000004 1.        ]]
[[0.000413 0.999587]]
[[0.0000006 0.9999994]]
[[0.00000084 0.99999917]]
[[0.00001416 0.99998

[[0.00004777 0.9999522 ]]
[[0.00000093 0.99999905]]
[[0.00009472 0.9999052 ]]
[[0.00118675 0.9988133 ]]
[[0.00004298 0.99995697]]
[[0.00001233 0.9999877 ]]
[[0.00001233 0.9999877 ]]
[[0.00020695 0.9997931 ]]
[[0.00052505 0.99947494]]
[[0.00164565 0.99835443]]
[[0.00049971 0.9995003 ]]
[[0.00000777 0.99999225]]
[[0.00004596 0.999954  ]]
[[0.0000017  0.99999833]]
[[0.00002332 0.99997663]]
[[0.00004884 0.9999511 ]]
[[0.00035979 0.9996402 ]]
[[0.00001556 0.9999844 ]]
[[0.00007902 0.99992096]]
[[0.00001621 0.9999838 ]]
[[0.00003125 0.99996877]]
[[0.00011463 0.9998853 ]]
[[0.0000084  0.99999166]]
[[0.00000009 0.9999999 ]]
[[0.01553275 0.98446727]]
[[0.00000678 0.9999932 ]]
[[0.00000678 0.9999932 ]]
[[0.02353142 0.97646856]]
[[0.02080108 0.9791989 ]]
[[0.00104905 0.99895096]]
[[0.0000011 0.9999989]]
[[0.00059758 0.9994024 ]]
[[0.00000004 1.        ]]
[[0.00000004 1.        ]]
[[0.00000069 0.9999993 ]]
[[0.00000065 0.9999994 ]]
[[0.00000014 0.9999999 ]]
[[0.00004082 0.99995923]]
[[0.00000052 0

[[0.00005842 0.9999416 ]]
[[0.00004107 0.9999589 ]]
[[0.00001021 0.99998975]]
[[0.00006997 0.99993   ]]
[[0.00014106 0.999859  ]]
[[0.00002562 0.99997437]]
[[0.0000253 0.9999747]]
[[0.00000728 0.9999927 ]]
[[0.00002051 0.9999795 ]]
[[0.0000156 0.9999844]]
[[0.00002259 0.99997735]]
[[0.00003144 0.9999685 ]]
[[0.00001294 0.999987  ]]
[[0.00004979 0.9999502 ]]
[[0.00002292 0.9999771 ]]
[[0.00001072 0.9999893 ]]
[[0.00001278 0.99998724]]
[[0.00001765 0.99998236]]
[[0.00005542 0.99994457]]
[[0.00000364 0.9999963 ]]
[[0.00000317 0.9999968 ]]
[[0.00000342 0.99999654]]
[[0.00000828 0.9999918 ]]
[[0.00000059 0.9999994 ]]
[[0.00000059 0.9999994 ]]
[[0.00000513 0.9999949 ]]
[[0.00005723 0.9999428 ]]
[[0.00001385 0.9999862 ]]
[[0.00002566 0.99997437]]
[[0.00002997 0.9999701 ]]
[[0.00045946 0.99954057]]
[[0.00144882 0.9985512 ]]
[[0.00007332 0.9999267 ]]
[[0.00002104 0.9999789 ]]
[[0.00000263 0.9999974 ]]
[[0.00018524 0.9998148 ]]
[[0.00000556 0.9999944 ]]
[[0.00000027 0.99999976]]
[[0.00000042 0.9

[[0.00015672 0.99984324]]
[[0.00001065 0.9999894 ]]
[[0.01347084 0.9865291 ]]
[[0.00000194 0.9999981 ]]
[[0.00000118 0.9999988 ]]
[[0.0010898 0.9989102]]
[[0.00264342 0.99735665]]
[[0.00812089 0.9918791 ]]
[[0.00000936 0.9999906 ]]
[[0.00000936 0.9999906 ]]
[[0.00000016 0.9999999 ]]
[[0.00000003 1.        ]]
[[0.00000639 0.99999356]]
[[0.000004   0.99999595]]
[[0.00004539 0.9999546 ]]
[[0.00001113 0.9999889 ]]
[[0.00000961 0.99999034]]
[[0.00000927 0.9999907 ]]
[[0.00000927 0.9999907 ]]
[[0.00089503 0.9991049 ]]
[[0.00004142 0.99995863]]
[[0.00030852 0.9996915 ]]
[[0.00097381 0.9990262 ]]
[[0.00000998 0.99999   ]]
[[0.00000514 0.9999949 ]]
[[0.0000009  0.99999905]]
[[0.00000189 0.9999981 ]]
[[0.00014822 0.9998517 ]]
[[0.00001679 0.9999832 ]]
[[0.00000254 0.9999975 ]]
[[0.00009301 0.999907  ]]
[[0.00003569 0.99996436]]
[[0.00000015 0.9999999 ]]
[[0.00000001 1.        ]]
[[0.0000002  0.99999976]]
[[0.00000086 0.99999917]]
[[0.00000049 0.9999995 ]]
[[0.00108831 0.99891174]]
[[0.00003812 0

[[0.00023545 0.9997645 ]]
[[0.0304991  0.96950084]]
[[0.00001239 0.9999876 ]]
[[0.00001239 0.9999876 ]]
[[0.00037243 0.9996276 ]]
[[0.00001467 0.99998534]]
[[0.00817416 0.9918258 ]]
[[0.00161899 0.998381  ]]
[[0.00000077 0.9999993 ]]
[[0.05697284 0.9430272 ]]
[[0.00000756 0.9999925 ]]
[[0.00000104 0.9999989 ]]
[[0.00001705 0.99998295]]
[[0.00001402 0.99998593]]
[[0.00001276 0.99998724]]
[[0.00002592 0.99997413]]
[[0.000004   0.99999595]]
[[0.00000001 1.        ]]
[[0.00000001 1.        ]]
[[0.00000083 0.99999917]]
[[0.00000018 0.99999976]]
[[0.00000027 0.99999976]]
[[0.00000191 0.9999981 ]]
[[0.00000366 0.9999963 ]]
[[0.00000253 0.9999975 ]]
[[0.00000002 1.        ]]
[[0.00000004 1.        ]]
[[0.00001527 0.99998474]]
[[0.00000002 1.        ]]
[[0.00000018 0.99999976]]
[[0.00000163 0.99999833]]
[[0.00000017 0.9999999 ]]
[[0.00054105 0.99945897]]
[[0.00012866 0.9998714 ]]
[[0.6319985  0.36800155]]
[[0.00005259 0.9999474 ]]
[[0.00002605 0.999974  ]]
[[0.00000055 0.9999994 ]]
[[0.00000289

[[0.00053392 0.9994661 ]]
[[0.0354441 0.9645559]]
[[0.00378518 0.9962148 ]]
[[0.00021893 0.9997811 ]]
[[0.00000213 0.99999785]]
[[0.00000011 0.9999999 ]]
[[0.00000011 0.9999999 ]]
[[0.00000102 0.9999989 ]]
[[0.00000118 0.9999988 ]]
[[0.00000099 0.99999905]]
[[0.00000001 1.        ]]
[[0.00000001 1.        ]]
[[0.00000028 0.99999976]]
[[0.00000312 0.9999969 ]]
[[0.00000081 0.99999917]]
[[0.44280723 0.55719274]]
[[0.00000176 0.9999982 ]]
[[0.00002612 0.9999739 ]]
[[0.00002612 0.9999739 ]]
[[0.00000009 0.9999999 ]]
[[0.00000001 1.        ]]
[[0.00000316 0.9999969 ]]
[[0.0000152  0.99998486]]
[[0.0000152  0.99998486]]
[[0.00001087 0.99998915]]
[[0.00000003 1.        ]]
[[0.00000001 1.        ]]
[[0.00000001 1.        ]]
[[0.00000531 0.99999464]]
[[0.00003235 0.9999677 ]]
[[0.00003235 0.9999677 ]]
[[0.00000403 0.99999595]]
[[0.00000403 0.99999595]]
[[0.00025785 0.9997421 ]]
[[0.00025785 0.9997421 ]]
[[0.01295253 0.98704743]]
[[0.00002058 0.9999794 ]]
[[0.00207805 0.997922  ]]
[[0.00207805 0

[[0.00000255 0.9999975 ]]
[[0.00000255 0.9999975 ]]
[[0.00002161 0.9999784 ]]
[[0.00000025 0.99999976]]
[[0.00000473 0.99999523]]
[[0.0000001 0.9999999]]
[[0.0000156 0.9999844]]
[[0.0000067 0.9999933]]
[[0.0000067 0.9999933]]
[[0.00029245 0.9997075 ]]
[[0.00033592 0.99966407]]
[[0.00001035 0.9999896 ]]
[[0.00001609 0.9999839 ]]
[[0.00001609 0.9999839 ]]
[[0.00021188 0.9997881 ]]
[[0.00014198 0.999858  ]]
[[0.00029007 0.9997099 ]]
[[0.00005863 0.99994135]]
[[0.00005863 0.99994135]]
[[0.00003392 0.999966  ]]
[[0.00004202 0.9999579 ]]
[[0.00000795 0.999992  ]]
[[0.00029305 0.9997069 ]]
[[0.00029305 0.9997069 ]]
[[0.00001065 0.9999894 ]]
[[0.00102506 0.9989749 ]]
[[0.00001603 0.999984  ]]
[[0.00000042 0.9999995 ]]
[[0.00001748 0.9999825 ]]
[[0.00001748 0.9999825 ]]
[[0.00000958 0.99999046]]
[[0.0000001 0.9999999]]
[[0.00000396 0.99999607]]
[[0.00032973 0.99967027]]
[[0.00016928 0.9998307 ]]
[[0.00003694 0.99996305]]
[[0.00003298 0.999967  ]]
[[0.00006984 0.99993014]]
[[0.00001153 0.9999884

[[0.00001681 0.9999832 ]]
[[0.00000666 0.9999933 ]]
[[0.00000105 0.9999989 ]]
[[0.00000007 0.9999999 ]]
[[0.00000022 0.99999976]]
[[0.00000467 0.99999535]]
[[0.00000008 0.9999999 ]]
[[0.00003608 0.9999639 ]]
[[0.00000007 0.9999999 ]]
[[0.00000004 1.        ]]
[[0.00000014 0.9999999 ]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0.00000013 0.9999999 ]]
[[0.00000633 0.9999937 ]]
[[0.00000101 0.99999905]]
[[0.00000024 0.99999976]]
[[0.00015275 0.9998472 ]]
[[0.00000601 0.99999404]]
[[0.00008764 0.9999124 ]]
[[0.0000002  0.99999976]]
[[0.00000024 0.99999976]]
[[0.00000011 0.9999999 ]]
[[0.00000078 0.99999917]]
[[0.00000024 0.99999976]]
[[0.00000055 0.9999994 ]]
[[0.00000015 0.9999999 ]]
[[0.00000076 0.9999993 ]]
[[0.00000023 0.99999976]]
[[0.00000118 0.9999988 ]]
[[0.00000076 0.9999993 ]]
[[0.00000013 0.9999999 ]]
[[0.00000637 0.9999937 ]]
[[0.00000758 0.9999924 ]]
[[0.00001779 0.99998224]]
[[0.00000389 0.99999607]]
[[0.0000018 0.9999982]]
[[0.00000182 0.9999982 ]]
[[0.00000402 0.99999595]]
[[0.000014

[[0.00000986 0.9999901 ]]
[[0.00002817 0.99997187]]
[[0.00000245 0.9999975 ]]
[[0.00001282 0.9999871 ]]
[[0.00000022 0.99999976]]
[[0.00000208 0.999998  ]]
[[0.00000095 0.99999905]]
[[0.00000031 0.99999964]]
[[0.00000008 0.9999999 ]]
[[0.00000007 0.9999999 ]]
[[0.00000002 1.        ]]
[[0.00000001 1.        ]]
[[0.00000009 0.9999999 ]]
[[0.00000054 0.9999994 ]]
[[0.00000054 0.9999994 ]]
[[0.00000049 0.9999995 ]]
[[0.00000062 0.9999994 ]]
[[0.00000385 0.9999962 ]]
[[0.00005319 0.99994683]]
[[0.00002032 0.99997973]]
[[0.00002032 0.99997973]]
[[0.00792264 0.9920773 ]]
[[0.92857254 0.07142745]]
[[0.02222019 0.97777987]]
[[0.02222019 0.97777987]]
[[0.11944798 0.88055205]]
[[0.10124942 0.89875054]]
[[0.00994943 0.99005055]]
[[0.00000098 0.99999905]]
[[0.00000053 0.9999995 ]]
[[0.00001502 0.999985  ]]
[[0.00002734 0.9999727 ]]
[[0.00000904 0.99999094]]
[[0.00000904 0.99999094]]
[[0.00000014 0.9999999 ]]
[[0.9909915  0.00900848]]
[[0.00000696 0.9999931 ]]
[[0.00000001 1.        ]]
[[0.00000092

[[0.01627651 0.9837235 ]]
[[0.00014057 0.99985945]]
[[0.00229316 0.9977068 ]]
[[0.00000136 0.9999987 ]]
[[0.00000136 0.9999987 ]]
[[0.00002308 0.9999769 ]]
[[0.00006977 0.99993026]]
[[0.00000658 0.99999344]]
[[0.00001126 0.9999888 ]]
[[0.00001126 0.9999888 ]]
[[0.00002416 0.9999758 ]]
[[0.00000302 0.999997  ]]
[[0.00000001 1.        ]]
[[0.00021322 0.9997868 ]]
[[0.00001729 0.9999827 ]]
[[0.00044522 0.9995548 ]]
[[0.00000092 0.99999905]]
[[0.00000029 0.99999976]]
[[0.00000012 0.9999999 ]]
[[0.00000012 0.9999999 ]]
[[0.00000005 1.        ]]
[[0.00009967 0.99990034]]
[[0.00009967 0.99990034]]
[[0.00000226 0.99999774]]
[[0.00000226 0.99999774]]
[[0.00000421 0.9999958 ]]
[[0.00000064 0.9999994 ]]
[[0.00000306 0.9999969 ]]
[[0.00000204 0.999998  ]]
[[0.00001027 0.99998975]]
[[0.00006985 0.99993014]]
[[0.00000004 1.        ]]
[[0.00000174 0.9999982 ]]
[[0.00000174 0.9999982 ]]
[[0.00006961 0.9999304 ]]
[[0.00001418 0.9999858 ]]
[[0.0000119 0.9999881]]
[[0.00000064 0.9999994 ]]
[[0.00024658 0

[[0.00038075 0.99961925]]
[[0.00012137 0.99987864]]
[[0.00055207 0.9994479 ]]
[[0.00000184 0.9999982 ]]
[[0.00647967 0.9935203 ]]
[[0.00647967 0.9935203 ]]
[[0.00017498 0.99982506]]
[[0.00007177 0.99992824]]
[[0.00079952 0.9992005 ]]
[[0.00321405 0.996786  ]]
[[0.00321405 0.996786  ]]
[[0.00134825 0.9986518 ]]
[[0.00009299 0.999907  ]]
[[0.00002576 0.99997425]]
[[0.0003171 0.9996829]]
[[0.0003171 0.9996829]]
[[0.00000415 0.9999958 ]]
[[0.00003936 0.99996066]]
[[0.00000042 0.9999995 ]]
[[0.00000006 1.        ]]
[[0.00000006 1.        ]]
[[0.00000038 0.99999964]]
[[0.00000061 0.9999994 ]]
[[0.00000002 1.        ]]
[[0.0000001 0.9999999]]
[[0.0000001 0.9999999]]
[[0.0000003  0.99999964]]
[[0.00000093 0.99999905]]
[[0.00000031 0.99999964]]
[[0.00000748 0.9999925 ]]
[[0.00000019 0.99999976]]
[[0.00024573 0.99975425]]
[[0.00002009 0.99997985]]
[[0.00000169 0.99999833]]
[[0.0000102  0.99998975]]
[[0.00020418 0.99979585]]
[[0.00002937 0.9999707 ]]
[[0.00002834 0.9999716 ]]
[[0.00383416 0.99616

[[0.00000001 1.        ]]
[[0.00000028 0.99999976]]
[[0.00000036 0.99999964]]
[[0.00000007 0.9999999 ]]
[[0.00000076 0.9999993 ]]
[[0.00000519 0.99999475]]
[[0.00000351 0.99999654]]
[[0.00000203 0.999998  ]]
[[0.0000013 0.9999987]]
[[0.00002223 0.9999777 ]]
[[0.00000048 0.9999995 ]]
[[0.0000901 0.9999099]]
[[0.00000191 0.9999981 ]]
[[0.00265694 0.9973431 ]]
[[0.00022083 0.99977916]]
[[0.00026589 0.9997341 ]]
[[0.00008 0.99992]]
[[0.00003171 0.9999683 ]]
[[0.00034337 0.9996567 ]]
[[0.00032814 0.9996718 ]]
[[0.00010502 0.999895  ]]
[[0.00016677 0.9998332 ]]
[[0.00134023 0.99865973]]
[[0.00008695 0.9999131 ]]
[[0.00036487 0.9996351 ]]
[[0.00035894 0.99964106]]
[[0.00004812 0.99995184]]
[[0.00016924 0.9998307 ]]
[[0.00008063 0.9999194 ]]
[[0.00037829 0.9996216 ]]
[[0.00213157 0.9978684 ]]
[[0.00003616 0.9999639 ]]
[[0.0000313  0.99996865]]
[[0.00010431 0.9998957 ]]
[[0.00014454 0.9998554 ]]
[[0.00006342 0.9999366 ]]
[[0.00086981 0.9991302 ]]
[[0.00003896 0.999961  ]]
[[0.00001042 0.9999896